### ISSUE TITLE
Lazy load "My library"

### ISSUE THREAD

**Issue by ghost** [lutris/website#116]
For me (> 500 games) it takes quite a time (> 10s !) to load the "My Library" page (> 6 MB!)

Possible fixes: 

- Load images lazily
- Load all games lazily in 10-game-batches or something like that (Use the API, that is)
- In any way, images should be loaded separately

Also I noticed an inconsistency:

The page is called "My Library" in the menu, "Library" in the heading, and "My games" in the title. I think it should be unified to "My Library" everywhere.

**Comment by strycore** [comment]
yeah, that needs to be redone entirely, considering using Polymer for it.

**Comment by charlydelta** [comment]
Yes that would be the best solution since we already depend on it.

Generally I think that this is the way to go: it's great to have a well defined API and the website consuming it via JSON. 
The project could then be splitted into 3 parts in the end: desktop-client, web-client and API. 

That would be a nice modular design and we should push towards it in the long run - at least that's my opinion.

Have you ever written a frontend application with angular, for example? The framework is awesome and typescript is such a beautiful language. And we could even couple both clients that way: views from the webclient could be used in the desktop client, like searching and adding games to ones library; updating and submitting installer scripts, etc. The frontend code can be cached by the desktop client.

Sorry for the wall of text, I obviously really like planning in the long run :D
