### ISSUE TITLE
Allowing cryptocurrency donations

### ISSUE THREAD

**Issue by einsteinsfool** [lutris/website#141]
It would be cool if you considered allowing people to donate to you in cryptos, like Bitcoin Cash or Monero.
I suggest Bitcoin Cash because it's popular and has low transaction fees and Monero because it's the most privacy-focused crypto.

You like Linux, many crypto enthusiasts like Linux. Some of them might donate.

And the setup shouldn't take long if you want to use a light wallet. Let me know if you have any questions.

**Comment by strycore** [comment]
cryptocurrency is bad.

**Comment by einsteinsfool** [comment]
That's narrow-minded, but you'll change your opinion sooner or later.
There are some bad cryptocurrencies, though, that are centralized. But in general cryptocurrency will free the world from governments manipulating the currency. No more inflation.

**Comment by Turupawn** [comment]
Lol just curious, why you don't like crypto @strycore ?
Is it because all that speculative wave on place at the moment?

**Comment by strycore** [comment]
Cryptocurrency doesn't solve any problem, it just causes pollution. 
Also, I added a bitcoin link to the donation page and no one has ever used it.

**Comment by einsteinsfool** [comment]
Please let me know if you're not interested in this conversation.

If cryptocurrency doesn't solve any problem, why is it popular? Are so many people wrong? Of course a lot of them are there for the speculation but only Ponsi schemes are *just* speculation. So it has to have use if it has value. And that value is decentralization. No-one can print more BCH which governments like to do with money from time to time. Take Venezuela for example. That could be fixed with gold standard but with crypto is out of the box and you can't get rid of it. Not to mention getting rid of the expensive intermediary which are banks. Instant transactions (and cheap for BCH and XMR) that can't be rejected. Some of them also allow for anonymity allowing you to buy sex toys and no bank/gov would know. And the anonymity increases the fungibility as one XMR is indistinguishable from another.

**Comment by strycore** [comment]
Crypto is a scam. It's only popular because people are stupid and gullible.

**Comment by cloud-8** [comment]
Wow its 2020 how can you have such a hilariously outdated view on crypto? I think youll find its government issued currencies that are the scam.... Anyway I wanted to donate, looked for the bitcoin link, googled and found this post, saw your attitude, then decided no thanks won't be donating to this. I suggest in future you enable people to fund the project with as many payment methods as possible, they literally want to give you money. Enjoy your Patreon/Paypal fees. @strycore

**Comment by belkka** [comment]
> saw your attitude, then decided no thanks won't be donating

<details>
<summary>
that's rude...
</summary>
Wow it's 2023 how can people be so arrogant? When I've seen your cool nickname and avatar I immediately wanted to send you 100 thousands of millions tons of gold, but then I read the whole comment and decided, no, thanks, won't be sponsoring this :) BTW, it was 2019, not 2020 when they were discussing the topic.
</details>

> Crypto is a scam. It's only popular because people are stupid and gullible.

So are banks and paper money, since they are not backed by gold... :sweat_smile: 

Some people consider cryptocurrencies as [the only?] private alternative to other modern payment methods. Giving them such a choice (1) should not harm — as soon as they know what they do — and (2) could be valuable for those concerned about privacy. No doubt, everyone, including lutris maintainers, has a right to not use whatever tools they are not comfortable with... As a compromise solution I believe it it's totally acceptable to publish a personal comment along with requisites, e.g.

> [disclaimer] Personally I don't like/trust/encourage/am not comfortable with *payment method XYZ*, but people were asking so you are free to use it if you really want: \*Requisites\*

FYI, personally I don't know much about crypto and have never used it. I'm fine with current state of things and not inviting anyone to conversation, just sharing my thoughts.

<details>
<summary>Speaking of privacy and Internet-safety, (off topic...)</summary>

I highly recommend https://nbtv.media. They also have some videos about crypto, none of which I've seen though; but I watched their videos on other topics and can say they are really good in explaining things.
</details>

**Comment by strycore** [comment]
The nice thing is that in 2023, we are no longer constantly being annoyed by Bitcoin. It's still a thing but cryptobros have been such a nuisance over the past few years that pretty much no one ever listens to them anymore.

I don't care much about the privacy aspect of donations. The amount of donation on Patreon is a public figure, and we publicize when an organization gives us money. 

What I care about is being able to easily use the donations to do things like : pay my rent, buy food and wine (the drinkable kind), Steam Decks and other things that are not anyone's concern. From my understanding, transactions on the blockchain are not really private... There are lots of flaws in the current banking system but at some point, we have to admit that cryptocurrencies are not a good solution to those flaws. Just because something is imperfect, doesn't mean it's not possible to create an alternative that's worse. If I want a transaction to remain private, I pay in cash, not in crypto.

**Comment by strycore** [comment]
I notice the value of Bitcoin is up to 40k, which isn't good. The last thing we need is yet another GPU shortage. I'm personally good on GPUs for the next few years but Lutris is about helping others play video games, and buying GPUs at a normal price is part of the equation. 

Now if someone approached me offering a sizeable donation in crypto, would I reconsider my position? Yeah, probably. Like I said previously, we used to have a bitcoin address on the donation page and it's never been used. My experience with crypto has been so poor, even leaving aside any ethical or ecological matters, that it's just not worth it when dealing with a few dollars worth of cash.

**Comment by danieljohnson2** [comment]
>  buy food and wine (the drinkable kind),

You can *drink* it?!

*This changes everything!*
