### ISSUE TITLE
Collapse game descriptions or limit max character number

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#150]
Game descriptions should be collapsible or limited to a certain amount of characters. Descriptions such as this one for [OOTP 19](https://lutris.net/games/out-of-the-park-baseball-19/) are absurdly long.

**Comment by strycore** [comment]
The descriptions shouldn't be collapsed because they shouldn't be that long to begin with.
There is a lot of cleanup to do in our data but some of it can be automated. The end goal would be to make all the long descriptions shorter.
We can also enforce a shorter description length in the UI without changing our database schema to prevent future submissions of overly long descriptions.
