### ISSUE TITLE
Can't Run Libretro/Retroarch from Lutris on Linux Mint 18.3 with right click

### ISSUE THREAD

**Issue by ajstrobus** [lutris/website#159]
-After installing lutris, & installing Libretro in Lutris runner manager, right clicking libretro & selecting Run doesn't seem to do anything.

-Going to ~/.local/share/lutris/runners/retroarch in terminal & manually running ./retroarch returns "./retroarch: error while loading shared libraries: "library file here": cannot open shared object file: No such file or directory.

-Lutris seemed to be missing 3 library files, not sure why but here they are. I installed with package manager & ./retroarch runs & runs with fonts fine in lutris as well.
     -libsdl2-2.0-0
     -libcg
     -libcggl

**Comment by strycore** [comment]
That is very surprising since all those libraries are included in the Lutris runtime. You shouldn't get that error unless you previously disabled the Lutris runtime manually beforehand.

Also, the Retroarch build we ship is intended to be executed from Lutris, you can try launching it externally but that will result in a bunch of missing libs, as you already experienced.

**Comment by AlexanderRavenheart** [comment]
Closing this as it is not relevant to the website.
Should be recreated on the Lutris project if this is still an issue.
