### ISSUE TITLE
search function is missing results

### ISSUE THREAD

**Issue by LimecK** [lutris/website#181]
Example: 

Searching for RiME will not list the Game

` https://lutris.net/games/?q=rime`

but Game entry exists in the Database

`https://lutris.net/games/rime/`

**Comment by luthub** [comment]
It's because there is no installer available for the game. Without an installer it is considered to be "unpublished". If you check the "Show unpublished games" box, it will appear in the results.
https://lutris.net/games/?unpublished-filter=on&q=rime

If someone writes an installer for it that gets accepted it will also appear in the "normal" search results

**Comment by LimecK** [comment]
Good to know, thank you.
