### ISSUE TITLE
Each suggested change reuploads the game banner

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#255]
With each user submitted change the game banner gets reuploaded even if it's not touched.

**Comment by fgblomqvist** [comment]
The reason this happens is because the tool that is used, django-croppie, [automatically sets the hidden form field](https://github.com/dima-kov/django-croppie/blob/master/croppie/static/croppie/form-process.js#L23-L31) to the image anytime you hand croppie an image (which occurs when the page first loads, naturally). I see three different solutions:

1. Modify django-croppie to take an option to not set the form field when the initial image (aka. existing) is loaded.
1. Compare the hashes of the submitted file and the existing file, if they're the same, ignore the submitted file.
1. Move the cropping part to a modal. I.e. only a static image (the existing one) will be shown directly on the form, and if someone wants to update/change it, they click a button to do so, which opens a modal, which allows them to upload a new image and crop it. That way, they also wouldn't be able to simply recrop the existing image (which I do find kinda odd UX-wise). If they for some reason really wanted to just crop the existing image, that can easily be done by just saving it, then reuploading it. I think this way would minimize the amount of "oops I accidentally edited the existing image"-cases.

The best option here, UX-wise, is 3 imo. However, the easiest one is probably 1.

**Comment by strycore** [comment]
django-croppie has been removed entirely, this is no longer an issue
