### ISSUE TITLE
Editor showing first draft only no matter the revision

### ISSUE THREAD

**Issue by AccountOneOff** [lutris/website#346]
This shit trippin

https://streamable.com/lv8jn

**Comment by T0MuX** [comment]
Hi, I do a little up because I'm having exactly the same issue (and very probably a lot of users).

I explain my case : I just did a fork of a script (BeamNG.drive)... the goal is to provide an installation script working with the alone game (I mean, not bought on steam). I do all my modifications, and "save draft" then, "test this installer" to check. Observing some errors and such.....
Ok, come back on lutris.net, "Edit script", fix the errors, and "Test this installer" again to check.... and here we go my script is working ! Then I clic on Save Draft, and Submit to moderation....
BUT ! Now, when I clic on "View script" I see the first script (just after the fork), so I'm like "oh god, where are my modifications ??", and if I clic on Edit script, I can saw my very last script version with all modifications (the good one so).

To me, it's a kind of a bit urgent to fix.

Thank you by advance !

**Comment by strycore** [comment]
I believe this has been fixed

**Comment by T0MuX** [comment]
You believe or you are sure  ? 😊

**Comment by strycore** [comment]
Given the recent updates, it is for sure!
