### ISSUE TITLE
The Publisher and Developer are not correctly sent

### ISSUE THREAD

**Issue by Steinhagen** [lutris/website#363]
Sometimes the Developer and Publisher are not correctly saved. 
In the following example the only modifications were:
- Added the "Publisher" and "Developer" fields.
- Zoomed in on the banner (by mistake), then (maximum) zoomed out to make sure that the image is not modified.

 As it can be seen from the diff change, not only that the developer/publisher fields were not created, but there is a "banner" change.

![dandp](https://user-images.githubusercontent.com/4029937/59313881-669f4e00-8cbb-11e9-8d2e-85727169e6e6.png)

**Comment by fgblomqvist** [comment]
The banner change issue was reported in #255 (I believe it's due to how the cropping tool is implemented).

As for the publisher/developer fields, they are not listed as fields that can be edited by users (e.g. they should be added there):
https://github.com/lutris/website/blob/master/games/models.py#L172

They should also be added here (for their values to populate in the forms, they currently don't):
https://github.com/lutris/website/blob/master/games/models.py#L263-L273

Finally, this function needs to be modified to actually set the suggested values (this happens when the moderator approves the change):
https://github.com/lutris/website/blob/master/games/models.py#L299-L308

I am new to the code of this project (and not a Django-expert) but I could submit a PR for this in the coming days. Fan of the client/site and it looks like @strycore could use some help (it's a huge project to manage by himself, big kudos to him) :)

**Comment by fgblomqvist** [comment]
Actually, the publisher/developer submission bug was reported in #250.

**Comment by fgblomqvist** [comment]
Opened #367 that fixes this.
