### ISSUE TITLE
Display hint that results contain unpublished entries when searching for games

### ISSUE THREAD

**Issue by legluondunet** [lutris/website#380]
Hello,
it's not the first time I had this issue on Lutris website: I searched for a game on Lutris site that gave me no result. So I decided to add this new game to the database.
I filled in the different fields of the form and click on "submit" and...I obtained this message: the game is already in our database...I loose my time several times on this issue. Example: Alone in the Dark 2, Age of Empire (first title),  etc...

**Comment by strycore** [comment]
By default, unpublished games and games with no installer are not displayed in the search results (because there is no way to use or install them). Currently, you have to check the "Show unpublished games" option in the advanced search features.
If no search results are returned, we do have an indicator that we have a game in database with the option to show it but there is nothing if we have search results to display.

We should have a way to give a hint that some games are not shown while still showing only installable games by default.
