### ISSUE TITLE
Selecting an installer on the website won't preselect it in the client

### ISSUE THREAD

**Issue by Xodetaetl** [lutris/website#44]
You've made so that all installers show up in the install game dialog after you've clicked some Install button on the website but the client doesn't preselect this installer, it just preselects the first in the list.

Edit: Er... I should probably have put this in client issues.

**Comment by strycore** [comment]
This is either a client or a website issue but given how we link installers currently, it's impossible for the client to know which game was selected. One solution could be to remove the install buttons on each separate installer and put just a single one on top or on the side.
My take on this is to leave it as is for this release so that users have time to update to 0.3.7 then we can think of a new url scheme for 0.4.0 (probably install/{game-slug}/versions/{version-slug})

**Comment by Xodetaetl** [comment]
> One solution could be to remove the install buttons on each separate installer and put just a single one on top or on the side.

This would be a regression. I'd rather drop the version selection step in the client after choosing on the website. It seems like the most sensible choice to me.

**Comment by strycore** [comment]
But this isn't possible with auto-installers. Well, it kinda is, I had written some very sketchy code to find the auto-installer based on game-slug-version-slug before deciding to remove the version-slug from all links. It's still possible to implement this, even if it's a very hacky solution.

**Comment by Xodetaetl** [comment]
The quality of the result is more important than the quality of the code, so if it works fine for the end user, dirty code gets the greenlight from me.

**Comment by strycore** [comment]
alright, I'll deploy this soon

**Comment by Xodetaetl** [comment]
Are you planning to do it before the 0.3.7 release?
It would be nice, because that's the kind of annoyance that everyone will notice.

**Comment by strycore** [comment]
Fixed and deployed!
