### ISSUE TITLE
Sync with SteamDB Linux entries

### ISSUE THREAD

**Issue by RobLoach** [lutris/website#46]
https://github.com/SteamDatabase/SteamLinux

We could query [GAMES.json](https://github.com/SteamDatabase/SteamLinux/blob/master/GAMES.json), to automatically ensure all Steam-linux supported games already have [Lutris](https://lutris.net/) entries.

**Comment by strycore** [comment]
Oh, that's really cool! I had written a small crawler with scrapy that would search in steamdb.info for Linux compatible games and automatically create Linux installers. I have only run this crawler once, a very long time ago and I have since then lost the code for it. 
I still have the code to create the installers from a json file so all I have to do is adapt it a little and setup a cron job to run it every couple days.

**Comment by AlexanderRavenheart** [comment]
Any progress on this?

**Comment by strycore** [comment]
There is now a script to import from this specific JSON, problem is that it doesn't seem maintained anymore.
If you know of any other source that can provide appids for new steam games, it wouldn't be too hard to adapt.
