### ISSUE TITLE
Bad reference to Lutris logo in base email template

### ISSUE THREAD

**Issue by caramat** [lutris/website#475]
The logo link in the base email template seems to be outdated since it does not load and throws an 404 error.
https://github.com/lutris/website/blob/ba7c5b8f06e4735b98e29834fd11683fd8a0118a/templates/emails/base.html#L19
The result of the above URL is [https://lutris.net/static/images/logo-header.png](https://lutris.net/static/images/logo-header.png) so it may have to be updated.

**Comment by sonic2kk** [comment]
I had a look and this seems to be because `{{ STATIC_URL }}` references the `public/` directory. Not only does the logo-header file not exist, but there is an XCF file (mostly used by GIMP) of the same name in the `frontend/image` directory.

I made a fork and I tried putting the `logo-header.png` file in the `public/images` directory. I haven't been able to get it to work, or loading any new images in that folder for that matter. I believe to have diagnosed the source of the problem, if anyone can offer me any insight it would be welcome!
