### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by resynth1943** [lutris/website#512]
Hello.

Could we find an alternative to Google Analytics? After some thinking, I've decided to raise my question here, which is: how can we, as a community, better the privacy of visitors to your website?

Lutris seems like an exceptional project (I've used it myself for GTA Vice City :D), would love some opinions here :-)

**Comment by strycore** [comment]
I have found an alternative to Google Analytics and it is currently in place. I have ELK installed on the same server as lutris and I should be able to get the same thing from this as we do on Google Analytics.
But my knowledge of Kibana is crap and I have the development of the lutris client to care of so haven't spent time teaching myself.
Because of that and since I still want some real time metrics about the website, I have left Google Analytics in place.
With a good Kibana dashboard, Google Analytics would go away very quickly.

**Comment by resynth1943** [comment]
> I have found an alternative to Google Analytics and it is currently in place

Oh nice!

> But my knowledge of Kibana is crap and I have the development of the lutris client to care of so haven't spent time teaching myself.

Oh, dang! What language is Kibana written in? Is it nonfree? I can see Amazon trying to sell it, but I'm not sure if that's just Elastic with some stickers on.

> Because of that and since I still want some real time metrics about the website

Fair enough ❤️ 
Thanks :D

**Comment by resynth1943** [comment]
Should we leave this issue open to track progress?

**Comment by strycore** [comment]
Yes, let's leave it open.
I'll write a summary of what I have done on the server and what's left to have parity with GA.

**Comment by resynth1943** [comment]
Thank you :D best of luck! ❤️

**Comment by LongJohn-Silver** [comment]
Why was this closed? I still see G Analytics in the website, it would be nice to reopen it until it gets merged.

Also, what about removing G Fonts, too, in the process so there is no proprietary dependencies?

**Comment by strycore** [comment]
The Google Analytics snippet must have been removed during the last big update of the website. I just removed the template snippet for GA but it wasn't referenced anywhere.

For the fonts, I'm not sure about that. That adds an extra 200k download at least and it's probably better to keep that on Google's CDN.
