### ISSUE TITLE
Autogenerate installers for steam runner

### ISSUE THREAD

**Issue by soredake** [lutris/website#567]
Creating installer for all new games is so annoying.

**Comment by strycore** [comment]
They are not even needed, you can install any Steam, Humble or GOG game from Lutris without an installer. Installers are only needed for special tasks during the game setup.

**Comment by soredake** [comment]
@strycore i tried to install game without installer from lutris client and get this https://github.com/lutris/agora/issues/94

**Comment by strycore** [comment]
yes because this is neither a Steam game, a Humble game or a GOG game. An installer won't magically appear.

**Comment by soredake** [comment]
Thanks, i get it now, if game has `Steamid` field than no installer is needed.

**Comment by soredake** [comment]
I hope lutris website will autoimport steam id's to games.

**Comment by strycore** [comment]
It's not exactly how that works anymore. Steamid is the legacy field, which we still use for the link to the store page and some other stuff. But the way we match games in the lutris client is with Game Providers which we have for Steam, GOG, HB and MAME (hopefully, we'll get a bunch more).
There is code to update all Steam and GOG IDs. Humble doesn't have an API to get all their games so that has to be maintained semi-manually.

Currently, everything that has a game provider should be installable in Lutris without needing an installer on the website. (The MAME service isn't implemented yet but it's planned)

Since everything that has a game provider is automatically installable in lutris, we should make it clear that this is the case on the game's page.
We have something similar for emulator auto-installers. I guess a small patch should be enough to generate auto-installers from game providers. 
It might also be wise to not use that legacy feature and only auto generate installer names. Auto-installers from the website do provide an install script but in this case, we want lutris to use its own self generated installer.

**Comment by strycore** [comment]
> I hope lutris website will autoimport steam id's to games someday.

that shouldn't be too hard... there is code to do that but it still needs to be setup as a periodic task (like every week). The problem is that the import task gets *all* Steam IDs, including all DLCs, movies, etc... I don't really want to auto create game pages for all those Steam IDs so right now we're only keeping those as references in Game Providers
