### ISSUE TITLE
Banned from Lutris.net by Cloudflare - how to unban?

### ISSUE THREAD

**Issue by Arteneko** [lutris/website#627]
It looks like Lutris decided to ban some computers in my home, but not all of them. Including on a dual-boot, the ban from linux is effective but not windows.

There is no way to contact anyone listed on the cloudflare ban page, I haven't done any suspicious activity (neither did any of my processes), and I'm stuck not able to install anything because of that.

How could a person blocked by this horrible MITM unblock themselves?

**Comment by strycore** [comment]
Send me your IP (can be by mail if you don't want to post it here) and I can have a closer look to why you would be blocked by Cloudflare.

**Comment by strycore** [comment]
I've had a look for the blocks from french IPs on the 29th of April and as far as I can tell, they're all from blocks I've personally put in place in the firewall due to suspicious activity.
Note that I no longer ban IPs but I ban whole AS number. Which means that you might not have done anything to get blocked but one of your neighbors did.
Or your IP changed to something that was previously blocked in the firewall. Still doesn't explain why you wouldn't be blocked in Windows.

**Comment by Arteneko** [comment]
Still getting blocked... Is there no way to avoid cloudflare's abusive policies ?

**Comment by strycore** [comment]
Don't blame Cloudflare, the IP you gave me was added to the firewall by me. (I usually do that when I see security scanners that generate a bunch of error 500, which I receive by mail)

 I removed the IP from the firewall rules so I'm surprised you're still blocked.
To try a workaround, open ~/.config/lutris/lutris.conf and add `website=https://lutr.is` in the `[lutris]` section.

**Comment by Arteneko** [comment]
Well, the error is provided by cloudflare, I can hardly blame something else...

Using lutr.is works well.

**Comment by strycore** [comment]
I've removed AS206092 from the Cloudflare firewall

**Comment by myviolinsings** [comment]
Thanks. Now I could download it.
