### ISSUE TITLE
Create aliases model for games

### ISSUE THREAD

**Issue by strycore** [lutris/website#64]
Add a model to store alternate names or common misspellings for game names so they can be redirected to the right page.

**Comment by charlydelta** [comment]
This wouldn't be necessary if we would rework the search, which is the best point to start imho (because the current search is way to strict). I was thinking about a fuzzy-search incorporating the levenshtein distance or similar word-edit-distances. Take a look at [this](https://michalcodes4life.wordpress.com/2014/06/03/full-text-search-and-fuzzy-search-with-postgresql-and-django/).
