### ISSUE TITLE
The anti-cheat message is still quite poor

### ISSUE THREAD

**Issue by LiamDawe** [lutris/website#694]
It's nice to see it was slightly updated to remove an opinionated bit but some more feedback. Again, I'm not suggesting to have no message, but keep it clear and concise. This could have literally been a single paragraph.

> Publishers claim those anticheats are necessary to combat cheaters and keep the game competitive. This is disproven by the fact there are still cheats easily available for such games.

If these games did _not_ have the anti-cheat, they would have vastly **more** cheats. Anyone who understands the industry knows this. It's just a thoroughly odd statement to have on the page. No the systems aren't perfect - but would you really want to play something like Fortnite, Destiny 2 or CoD without anti-cheat? They would be a cheaters playground.

> We urge you to stay away from those games, none of them are worth compromising the integrity of your machine.

Respectfully, is Lutris a game manager, or an opinionated place to tell people what they should and shouldn't play? It feels completely out of place.

> Stay safe and don't install malware on your machine, whether it's on Linux or Windows. Sometimes the cure is worse than the disease!

This again just seems totally out of place. Especially the second sentence, it's just...silly.

The entire anti-cheat message could have just been:

> This game has Windows kernel-level anti-cheat so it will **not** work on Linux. 

Simple, informative, non-lecturing.

Ref: https://lutris.net/games/destiny-2/

**Comment by strycore** [comment]
As usual, there is an initial uproar about those abusive anti-consumer features, whether it's loot boxes, Denuvo DRM or Kernel anticheats. Then as time passes, publishers push the boundaries of what becomes acceptable. 
Like this, kernel anticheats have gone from this dangerous menace to something that has been casually accepted by the gamers. While this is not surprising, it is still a disappointment. 

The disclaimer does not suggest to get rid of all anti-cheats, all the games we suggest as alternative also have anti-cheats that are to my knowledge just as effective as the kernel ones, without overstepping on the user's privacy and control of their machine.

Lutris has always been an opinionated platform, even if most of it gets ignored by the majority. The project advocates for preservation of our gaming legacy. I personally see it as a failure when people use Lutris for 5 or 6 non Steam games instead of building their game collection. Similarly, any hope of preserving games using those anti-cheats is futile, the game will disappear when the publisher decides to pull the plug. So yes, Lutris tells people they should play the games they grew up with and shouldn't play kernel AC games, even if the only reason is those games won't launch at all.

>   This game has Windows kernel-level anti-cheat so it will not work on Linux.

We've had such a warning on the Fornite installer for a long time. It has a rating of non playable. People still manage to ignore that. The disclaimer needs to be bold and obtrusive so it is too big to ignore.

There are some changes that I still have to push to prod and I'm willing to accept more changes but I don't want the message to be a watered down, neutral version of the current one.

**Comment by dpanter** [comment]
We know invasive anticheat rootkits are atrocious. Of course they are. 

If the project can't keep a neutral and professional tone in the advocacy for preservation of gaming legacy, it reflects poorly on the project and by extension everyone using or promoting it. This specific anticheat message comes off as childish, abrasive and hostile. Even after changing it to be less so.

I don't understand why you think Lutris should be the arbiter of which games people are allowed to enjoy. Some anticheats make games unplayable in Linux, that's how that is. It's not within Lutris remit to browbeat people with disparaging remarks about a game when they are looking for Linux compatibility info. You can't force people to absorb information by making the text larger or the wording more salty. 

In the larger picture where Linux gaming is starting to get some wind on its back, this is the kind of negative publicity that can help sink the ship instead. 
Can we please do better?

**Comment by mlavik1** [comment]
@strycore  If I were you, I'd y"

> We know invasive anticheat rootkits are atrocious. Of course they are.
> 
> If the project can't keep a neutral and professional tone in the advocacy for preservation of gaming legacy, it reflects poorly on the project and by extension everyone using or promoting it. This specific anticheat message comes off as childish, abrasive and hostile. Even after changing it to be less so.
> 
> I don't understand why you think Lutris should be the arbiter of which games people are allowed to enjoy. Some anticheats make games unplayable in Linux, that's how that is. It's not within Lutris remit to browbeat people with disparaging remarks about a game when they are looking for Linux compatibility info. You can't force people to absorb information by making the text larger or the wording more salty.
> 
> In the larger picture where Linux gaming is starting to get some wind on its back, this is the kind of negative publicity that can help sink the ship instead. Can we please do better?

I find Lutris' message much less hostile than this comment. Also, nobody is forcing anyone to do anything. They're just warning their own users against installing software that may compromise their privacy.

It's entirely possible to give people feedback without being toxic - please try! Also, it wouldn't hurt to make a suggestion - because it's not at all clear from your comment what edits you'd like to see, or if you think the message should just be removed.

The only constructive suggestion I've seen is this thread so far is Liam's suggestion to replace the message with "This game has Windows kernel-level anti-cheat so it will not work on Linux.". I absolutely see the point, but that fails to provide any info on *why* the game doesn't work on Linux. To an unexperienced Linux user this might make it sound like this is a problem with Linux, and that they'd better use Windows if they want to play this game -  which may not be risk-free. You're free to disagree, but personally I think it's fair to warn your own users about problems that might be in their interest to know about. I don't find that unprofessional at all - Most privacy focused companies out there don't hesitate to criticise Google when they do something bad.

Of course, I'm sure the message can be improved further, to sound more "professional". Personally I think it's good enough after @ProfessorCode212's edits though.

**Comment by ProfessorCode212** [comment]
I actually agree with @mlavik1 in that we need to give some context as to why it doesn't work, but I think we can do without the part about publisher's claims regarding anti-cheat software (in the edited message). It does feel like a bit of stretch to say that anti-cheat software hasn't "stopped such cheating from occurring" in hindsight, although I did try to provide some proof with that news article.

**Comment by ProfessorCode212** [comment]
I think one option we haven't really considered is to keep the message on the game page short and then providing a link to a blog post where it can explained in more detail. This might actually offer the best of both worlds — Lutris gets to say its piece and users won't be annoyed either.

If not, the best option is to just scale down the size. We get to keep the content where everyone can still see it without being obtrusive.

**Comment by strycore** [comment]
I have reworded the disclaimer in a bullet list form. It conveys the same information while being less abrasive. 

The disclaimer used to show where the screenshots used to be. Now it also replaces the installer list in addition to the screenshots.

> It's hard to see anything else on that page.

There is absolutely nothing else to see on this page. It is the only piece of information that should be present.

**Comment by mlavik1** [comment]
Looks nice and clear to me at least :) Also doesn't feel so much like a wall of text anymore, thanks to the bullet points and bold text.

Personally I was fine with you clearly warning against playing these games on Windows, but if it makes other people so furious and hostile I guess it's not worth it :sweat_smile: 

Anyway, thanks for your hard work! Lutris is a life saver! <3

**Comment by LiamDawe** [comment]
Yeah that works much better and the language is much improved. Good stuff 👍
