### ISSUE TITLE
Provide auto-installers for Steam and GOG games

### ISSUE THREAD

**Issue by strycore** [lutris/website#79]
Steam  and GOG games (both Windows and Linux) run just fine with default settings. Provide auto-installers for those which can then be overridden (see #45 )

Display a warning saying the installer is an automated one.

**Comment by charlydelta** [comment]
So, how did you think to accomplish this? Auto-installers and platforms seem to be tightly coupled at the moment.

The problem is that this proves to be quite complex. A game can be released on Steam and GOG, but that does not mean that both distributions have the same platforms. For example, LIMBO was never released for Linux on GOG, but on Steam it was.

The easiest way to fix this would be to add new platforms like `Linux:GOG`, `Linux:Steam`, `Windows:GOG` and `Windows:Steam` in addition to the existing `Linux` and `Windows` platforms.

But this could easily clutter the views, especially if other distributions will be added, too, for example Humble Store, Desura, ...

However, a standard could be defined to separate namespaces. For example ':'. So, when the platforms are to be printed on the view, the platforms strings could be cut at ':' and grouped by whatever stands before ':'. The game detail view for LIMBO, for example, would then just print Linux and Windows. When you hover Linux, it would print: `Published on Steam`, and when you hover Windows it would print: `Published on Steam and GOG`.

What do you think?

**Comment by strycore** [comment]
Steam and GOG games now have auto-installers on the client
