### ISSUE TITLE
Contribute by editing game metadata

### ISSUE THREAD

**Issue by charlydelta** [lutris/website#98]
I noticed that a lot of meta data was missing, and so I wanted to contribute by submitting the missing data. I then noticed that you just offer a way to submit new games, but that there is no way to actually edit or at least complete the metadata of existing games. 

After a quick search I found [this thread from about a year ago](https://forums.lutris.net/t/submitting-steam-games/132/4), but it does not look like this has been implemented yet.

Is there another way which I have not found, or is it really not possible to improve the current database?

**Comment by strycore** [comment]
at this  point I'm only interested in code contributions.

**Comment by strycore** [comment]
(for implementing data submissions by users, that is.)

**Comment by christiandreher** [comment]
Initial submissions are implemented, editing is missing, right?

What are the general requirements for you regarding this issue?

- Should the data be editable by everyone? Or restricted in some way?
- Should changes be reviewed? If yes, by who? Moderators?
- What else to consider?

**Comment by strycore** [comment]
There is a basic form to submit games yes.
Now we need to have something to let users submit changes to existing games.

The submissions should not be saved directly to the database entry, they should be moderated first.
Since there are many fields that can be modified, we might just save the relevant changeset as JSON then apply it to the instance when validated. Anyone with a confirmed email address can make any kind of changes. Like we did for installers, there should be a way to lock down games so they're not editable anymore (can be skipped for the initial implementation).

We also need one or several forms added to the game details page that will present users with valid choices for submissions, depending on what is being submitted.

**Comment by christiandreher** [comment]
I will probably have time mid-october, so I could take a look at it.

**Comment by charlydelta** [comment]
Couldn't reach anybody on IRC, but i have to go now. Well, the MR is ready for feedback/review for this issue

**Comment by strycore** [comment]
Great! I will review it soon, many thanks for the great work!
